server:
  port: 8083

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri:
            lb://account-service
          predicates:
            -Path=/accounts/**, /account/**, /user/*/account/**, /creditCardApplication/**, /creditCardApplications/**, /creditCardType/**, /loanApplication/**, /loanApplications/**
          filters:
           - name: JWTFilter
        - id: authentication-service
          uri:
            lb://authentication-service
          predicates:
            - Path=/api/authentication/**
            - Method=POST

        - id: user-service
          uri:
            lb://user-service
          predicates:
            -Path=/user, /user/*
          filters:
            - name: JWTFilter
        - id: transaction-service
          uri:
            lb://transaction-service
          predicates:
            -Path=/transaction/**
          filters:
            - name: JWTFilter
